def theShow():
    print("              /\\")
    print("             /  \\")
    print("            /    \\")
    print("           00000000")
    print("           |  __  |")
    print("           | |++| |")
    print("           |  --  |")
    print("      |    |      |     |")
    print("     /\\    |      |    /\\")
    print("    /  \\   |      |   /  \\")
    print("   /    \\  |      |  /    \\")
    print("  00000000 |      | 00000000")
    print("  |  __  | |      | |  __  |")
    print("  | |++| | |      | | |++| |")
    print("  |  --  | |      | |  --  |")
    print("  |      | |      | |      |")
    print("  |      | |      | |      |")
    print("  |      | |      | |      |")
    print("  |      ---      ---      |")
    print("  |       |        |       |")
    print("  |       |________|       |")
    print("  |       |++++++++|       |")
    print("  |       |++++++++|       |")
    print("  |       |++++++++|       |")
    print("  |-------|--------|-------|")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    
    print("\nwill you open the gate?")
    print("press any key to continue...")
    input()
    print("              /\\")
    print("             /  \\")
    print("            /    \\")
    print("           00000000")
    print("           |  __  |")
    print("           | |++| |")
    print("           |  --  |")
    print("      |    |      |     |")
    print("     /\\    |      |    /\\")
    print("    /  \\   |      |   /  \\")
    print("   /    \\  |      |  /    \\")
    print("  00000000 |      | 00000000")
    print("  |  __  | |      | |  __  |")
    print("  | |++| | |      | | |++| |")
    print("  |  --  | |      | |  --  |")
    print("  |      | |      | |      |")
    print("  |      | |      | |      |")
    print("  |      | |      | |      |")
    print("  |      ---      ---      |")
    print("  |       |        |       |")
    print("  |       |________|       |")
    print("  |       |Welcome!|       |")
    print("  |       |  come  |       |")
    print("  |       | inside |       |")
    print("  |-------|--------|-------|")
    print("~~~~~~~~~~~++++++++~~~~~~~~~~~")
    print("~~~~~~~~~~~++++++++~~~~~~~~~~~")
    print("~~~~~~~~~~~++++++++~~~~~~~~~~~")
    print("\npress any key to continue...")
    input()
    print("             /--\\")
    print("            /----\\")
    print("           /------\\")
    print("          /--------\\")
    print("          |OOOOOOOO|")
    print("          |OOOOOOOO|")
    print("          |OOOOOOOO|")
    print("          |OOOOOOOO|")
    print("       WWW|OOOOOOOO|WWW")
    print("          |========|")
    print("          |88888888|")
    print("          VV      VV")
    print("          VV      VV")
    print("          VV      VV")
    print("\n    You are the new king!")
    print("press enter to play again")
    input()
    theShow()
theShow()
